language: python
python:
  - '3.8'

before_script:
  - pipenv shell

env: DJANGO_SETTINGS_MODULE="api_battlegrounds.settings.travis"

services:
  - postgresql

branches:
  only:
    - staging

script:
  - pytest tests/

