language: python
python:
  - '3.8'

before_script:
  - pipenv install
  - psql -c "CREATE DATABASE travisdb;" -U postgres

env: DJANGO_SETTINGS_MODULE="api_battlegrounds.settings.travis"

services:
  - postgresql

branches:
  only:
    - staging

script:
  - ./manage.py test

