# Generated by Django 3.2.9 on 2021-11-19 20:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('dbfId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('synergy', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, unique=True)),
                ('techLevel', models.IntegerField(blank=True)),
                ('attack', models.IntegerField(blank=True)),
                ('health', models.IntegerField(blank=True)),
                ('max_health', models.IntegerField(blank=True)),
                ('battlegroundsPremiumDbfId', models.IntegerField(blank=True)),
                ('battlegroundsNormalDbfId', models.IntegerField(blank=True)),
                ('cardClass', models.CharField(max_length=255)),
                ('cost', models.IntegerField(default=0)),
                ('mechanics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('referencedTags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('race', models.CharField(blank=True, choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], max_length=255)),
                ('set', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=4080)),
                ('power_id', models.IntegerField(blank=True)),
                ('ban', models.BooleanField(default=False)),
                ('can_collect', models.BooleanField(default=True)),
                ('battlegroundsHero', models.BooleanField(default=False)),
                ('remain_use', models.IntegerField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
