# Generated by Django 3.2.9 on 2021-11-21 18:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('dbfId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id', models.CharField(default='no_method', max_length=255)),
                ('techLevel', models.PositiveSmallIntegerField(default=0)),
                ('attack', models.PositiveSmallIntegerField(null=True)),
                ('health', models.PositiveSmallIntegerField(null=True)),
                ('max_health', models.PositiveSmallIntegerField(null=True)),
                ('battlegroundsPremiumDbfId', models.IntegerField(null=True)),
                ('battlegroundsNormalDbfId', models.IntegerField(null=True)),
                ('powerDbfId', models.IntegerField(null=True)),
                ('repopDbfId', models.IntegerField(null=True)),
                ('enchantmentDbfId', models.IntegerField(null=True)),
                ('cardClass', models.CharField(default='NEUTRAL', max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('mechanics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None)),
                ('referencedTags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None)),
                ('race', models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30)),
                ('synergy', models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30)),
                ('type', models.CharField(default='DEFAULT', max_length=30)),
                ('hero_script', models.CharField(max_length=255, null=True)),
                ('battlegroundsHero', models.BooleanField(default=False)),
                ('remain_use', models.PositiveSmallIntegerField(null=True)),
                ('avenge_counter', models.PositiveSmallIntegerField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('aura', models.BooleanField(default=False)),
                ('battlegroundsDarkmoonPrizeTurn', models.PositiveSmallIntegerField(null=True)),
                ('minion_cost', models.PositiveSmallIntegerField(null=True)),
                ('roll_cost', models.PositiveSmallIntegerField(default=0)),
                ('levelup_cost_mod', models.PositiveSmallIntegerField(default=0)),
                ('phase', models.CharField(max_length=30, null=True)),
                ('spellSchool', models.CharField(default='', max_length=30)),
                ('elite', models.BooleanField(default=False)),
                ('rarity', models.CharField(default='DEFAULT', max_length=30)),
                ('collectible', models.BooleanField(default=False)),
                ('set', models.CharField(max_length=30)),
                ('artist', models.CharField(default='', max_length=255)),
                ('text', models.CharField(default='', max_length=4080)),
                ('flavor', models.CharField(default='', max_length=4080)),
                ('targetingArrowText', models.CharField(default='', max_length=255)),
                ('howToEarn', models.CharField(default='', max_length=255)),
                ('howToEarnGolden', models.CharField(default='', max_length=255)),
                ('faction', models.CharField(default='', max_length=30)),
                ('hideStats', models.BooleanField(default=False)),
                ('hideCost', models.BooleanField(default=False)),
                ('collectionText', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
