# Generated by Django 3.2.9 on 2021-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_aura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
