# Generated by Django 3.2.9 on 2021-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='id',
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30, primary_key=True, serialize=False),
        ),
    ]
