# Generated by Django 3.2.9 on 2021-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20211119_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collectible',
            field=models.BooleanField(default=False),
        ),
    ]
