# Generated by Django 3.2.9 on 2021-12-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20211204_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.race'),
        ),
    ]
