# Generated by Django 3.2.9 on 2021-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_card_collectible'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='flavor',
            field=models.CharField(default='', max_length=4080),
        ),
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.CharField(default='', max_length=4080),
        ),
    ]
