# Generated by Django 3.2.9 on 2021-11-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='max_health',
            field=models.IntegerField(),
        ),
    ]
