# Generated by Django 3.2.9 on 2021-12-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_synergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='NONE', max_length=30, primary_key=True, serialize=False),
        ),
    ]
