# Generated by Django 3.2.9 on 2021-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_card_max_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='max_health',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='techLevel',
            field=models.IntegerField(null=True),
        ),
    ]
