# Generated by Django 3.2.9 on 2021-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20211205_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
