# Generated by Django 3.2.9 on 2021-12-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_rarity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.rarity'),
        ),
    ]
