# Generated by Django 3.2.9 on 2021-12-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(default='INVALID', on_delete=django.db.models.deletion.PROTECT, to='card.rarity'),
        ),
    ]
