# Generated by Django 3.2.9 on 2021-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_card_elite'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='howToEarn',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='howToEarnGolden',
            field=models.CharField(default='', max_length=255),
        ),
    ]
