# Generated by Django 3.2.9 on 2021-11-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20211119_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='avenge_counter',
            field=models.IntegerField(null=True),
        ),
    ]
