# Generated by Django 3.2.9 on 2021-11-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_card_avenge_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='faction',
            field=models.CharField(default='', max_length=255),
        ),
    ]
