# Generated by Django 3.2.9 on 2021-11-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_card_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='battlegroundsDarkmoonPrizeTurn',
            field=models.IntegerField(null=True),
        ),
    ]
