# Generated by Django 3.2.9 on 2021-11-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_card_battlegroundsdarkmoonprizeturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='spellSchool',
            field=models.CharField(default='', max_length=255),
        ),
    ]
