# Generated by Django 3.2.9 on 2021-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_card_bonus_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
