# Generated by Django 3.2.9 on 2021-11-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_card_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='aura',
            field=models.BooleanField(null=True),
        ),
    ]
