# Generated by Django 3.2.9 on 2021-11-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_card_aura'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hero_script',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
