# Generated by Django 3.2.9 on 2021-11-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0025_card_minion_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='roll_cost',
            field=models.IntegerField(null=True),
        ),
    ]
