# Generated by Django 3.2.9 on 2021-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0026_card_roll_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='levelup_cost_mod',
            field=models.IntegerField(null=True),
        ),
    ]
