# Generated by Django 3.2.9 on 2021-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0027_card_levelup_cost_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='zone_type',
            field=models.IntegerField(null=True),
        ),
    ]
