# Generated by Django 3.2.9 on 2021-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0029_card_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='zone_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
