# Generated by Django 3.2.9 on 2021-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0030_alter_card_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=255),
        ),
    ]
