# Generated by Django 3.2.9 on 2021-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0031_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='can_collect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardClass',
            field=models.CharField(default='NEUTRAL', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
