# Generated by Django 3.2.9 on 2021-11-20 11:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0032_auto_20211120_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='can_collect',
        ),
        migrations.AlterField(
            model_name='card',
            name='attack',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='aura',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='avenge_counter',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='battlegroundsDarkmoonPrizeTurn',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardClass',
            field=models.CharField(default='NEUTRAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='elite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='faction',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='levelup_cost_mod',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='max_health',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='mechanics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='minion_cost',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='phase',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='referencedTags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='remain_use',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='roll_cost',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='set',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='spellSchool',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='synergy',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='techLevel',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='NONE', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='zone_type',
            field=models.CharField(default='NONE', max_length=30),
        ),
    ]
