# Generated by Django 3.2.9 on 2021-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0034_alter_card_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
