# Generated by Django 3.2.9 on 2021-11-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0035_alter_card_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='can_collect',
            field=models.BooleanField(default=False),
        ),
    ]
