# Generated by Django 3.2.9 on 2021-11-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0036_card_can_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='ban',
        ),
        migrations.RemoveField(
            model_name='card',
            name='can_collect',
        ),
    ]
