# Generated by Django 3.2.9 on 2021-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0037_auto_20211120_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(default='no_method', max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='synergy',
            field=models.CharField(choices=[('ALL', 'ALL'), ('NONE', 'NONE'), ('BEAST', 'BEAST'), ('DEMON', 'DEMON'), ('MECHANICAL', 'MECHANICAL'), ('MURLOC', 'MURLOC'), ('DRAGON', 'DRAGON'), ('PIRATE', 'PIRATE'), ('ELEMENTAL', 'ELEMENTAL'), ('QUILBOAR', 'QUILBOAR')], default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='techLevel',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='card',
            name='zone_type',
            field=models.CharField(default='DEFAULT', max_length=30),
        ),
    ]
