# Generated by Django 3.2.9 on 2021-11-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0038_auto_20211120_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='enchantment_dbfId',
            new_name='enchantmentDbfId',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='power_dbfId',
            new_name='powerDbfId',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='repop_dbfId',
            new_name='repopDbfId',
        ),
    ]
