# Generated by Django 3.2.9 on 2021-11-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0039_auto_20211120_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='zone_type',
        ),
    ]
