# Generated by Django 3.2.9 on 2021-11-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0040_remove_card_zone_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='bonus_value',
        ),
    ]
