# Generated by Django 3.2.9 on 2021-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0041_remove_card_bonus_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='battlegroundsNormalDbfId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='battlegroundsPremiumDbfId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='enchantmentDbfId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='powerDbfId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='repopDbfId',
            field=models.IntegerField(null=True),
        ),
    ]
